#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
  echo "Usage: run_sample_docker_agent <container-id>"
  exit 1
fi

container_id="$(docker run -d -p 5000:5000 "$1")"

echo "Started running container $container_id"
exit 0